### ISSUE TITLE
Dashboard - Device 加上 MCU 目前支援的 Protocol

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1000]
# Why

- 因為很多 MCU MQTT with TLS 會有點問題, 這個部分可能要花很多時間排除, 所以目前先讓 MQTT 上到正式, 有支援 MQTT 的才顯示相對應的 Protocol

# Task

- [ ] API mcu table 加上 supported_protocol
- [ ] Dashboard 有出現的 protocol 才顯示在下拉選單

# Check List

- [ ] Dashboard `/devices/edit/{deviceId}`  下拉選單只有 ESP-01S 會顯示 MQTT 其他的都直接顯示文字 HTTP
