### ISSUE TITLE
Dashboard - 實作 log api 紀錄重開機次數

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1029]
# Why
- 目前要解決 Arduino nano 33 IoT 一段時間會重開的問題，但目前不知道重開的頻率是否有規律，所以記錄一下重開機的狀況是否很嚴重

# Task

- [ ] 實作 Log API for device 
  - [ ] 開一個 log table, log 有以下欄位 Id, CreatedAt, DeviceId
  - [ ] 新增 log RESTful API

# Check List

- [ ] 上方任務都完成，可以透過 Postman 新增一筆 Log
