### ISSUE TITLE
Dashboard - 加上 pipeline

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1059]
# Why
補足 Trigger 無法做複雜的判斷，包含某時刻, Sensor 感測數值, delay, 平均, 標準差, 中位數

# Task

- [x] 研究 Flow 相關的套件
- [x] API Pipeline Item:
  - [x] Time Driven
  - [x] Notification
  - [x] Switch
  - [x] Check Switch
  - [x] Delay
  - [x] Aggregate
    - [x] SUM
    - [x] STD
    - [x] AVG
    - [x] 中位數
- [x] Dashboard Pipeline Item UI
  - [x] Dashboard Pipeline F2E Validation
  - [x] Dashboard Dirty Form Icon
  - [x] 優化 Icon 
- [x] API Starup 加上 Schedule Pipeline Execute 
- [x] API 加上使用上限, 目前規劃是免費會員每天只能執行一次
- [x] API 實作 Pipeline Execute Log 
- [x] API Pipeline 加上 Offline Pipeline
- [x] Dashboard Pipeline 加上 Offline Pipeline
- [x] Offline Pipeline 加上 Validation
- [x] 當今天是多台主機時，只有一台主機會跑 Pipeline lock-free pattern
- [x] Refactor Code

# Check List
- [ ] 檢查上方功能是否正常

**Comment by vickychou99** [comment]
1. 至 `編輯 Pipeline` 時，connectors 的線，沒有完整顯示，目前只顯示開頭的第一條線連到的下一個 ITEM，已確認 API 有正常拿到資料，但線沒有正常顯示，如下影片

https://user-images.githubusercontent.com/9404692/222641275-b7640740-365a-4e9a-91a6-d26fee32a725.mp4

**Comment by vickychou99** [comment]
至 `編輯 Pipeline` 時，尚未新增任何 block 時，點 toggle 的箭頭執行 Pipeline 時，會顯示錯誤訊息，請改成 toaster 提醒
<img width="1440" alt="截圖 2023-03-03 下午1 50 12" src="https://user-images.githubusercontent.com/9404692/222642393-7f35da53-42ce-4a5e-869f-e5c4eb00389f.png">

**Comment by vickychou99** [comment]
`編輯 Pipeline `時，類型選擇 `感測器` 之後， 只需顯示感測器的 PIN (IO2)，不需顯示開關的 PIN (RX)。
若類型選擇 `開關` 、`檢查開關狀態`，只需顯示開關的 PIN (RX)

<img width="501" alt="截圖 2023-03-03 下午1 57 30" src="https://user-images.githubusercontent.com/9404692/222642853-4649c87a-43af-41eb-b943-3759c440b352.png">

<img width="515" alt="截圖 2023-03-03 下午1 58 35" src="https://user-images.githubusercontent.com/9404692/222643042-263ff54c-9fac-4076-b2db-f4a69d714989.png">

**Comment by vickychou99** [comment]
類型選擇 `檢查開關狀態` 時， 文字 `控制` 改成 `檢查開關狀態為`

<img width="327" alt="截圖 2023-03-03 下午2 04 35" src="https://user-images.githubusercontent.com/9404692/222643959-5c443aae-c336-4054-9dee-51b86cdf433a.png">

**Comment by vickychou99** [comment]
pipeline 在運行狀態的時候，應該不能開放修改

<img width="757" alt="截圖 2023-03-03 下午2 14 52" src="https://user-images.githubusercontent.com/9404692/222645719-f1fc6359-f155-467e-b6dc-f7389365a1b4.png">

**Comment by vickychou99** [comment]
`pipeline 列表頁`，增加顯示 pipeline isRun 的狀態
<img width="766" alt="截圖 2023-03-03 下午2 19 43" src="https://user-images.githubusercontent.com/9404692/222646215-89765a45-6786-4eff-b782-acc48ad6b75e.png">

**Comment by vickychou99** [comment]
`編輯 Pipeline`的通知 item 沒有正常的 binding 資料

<img width="1440" alt="截圖 2023-03-03 下午2 24 47" src="https://user-images.githubusercontent.com/9404692/222647262-82119be4-87bc-4bb6-a48b-dff05e2e5d82.png">

<img width="530" alt="截圖 2023-03-03 下午2 24 28" src="https://user-images.githubusercontent.com/9404692/222646951-882cb152-0e33-4c80-8694-dab20b56a08e.png">

**Comment by vickychou99** [comment]
移除名稱旁的 false
<img width="884" alt="截圖 2023-03-03 下午1 50 01" src="https://user-images.githubusercontent.com/9404692/222650856-9f5f9a87-a2c3-4673-a5cc-468ae3d918b7.png">

**Comment by vickychou99** [comment]
測試 pipeline head 為感應器，設定完後發現沒有正常運作，比對資料後發現 FirstPieplineItemType = 0 (SCHEDULE)
MyDevicePinSensorController.cs 行 70，撈出來的資料為空，所以 pipeline 沒有正常運作

另外程式中找不到 firstPipelineItemType 是在哪個時候被更新的，猜測後面都用 PipelineHelper.GetHead 捉 Head 的 PipelineItemType，就沒有在用 firstPipelineItemType 了。

<img width="973" alt="截圖 2023-03-03 下午4 22 26" src="https://user-images.githubusercontent.com/9404692/222669031-8e887064-0766-4c1b-b15d-d4baae978e1f.png">

**Comment by miterfrants** [comment]
> `編輯 Pipeline `時，類型選擇 `感測器` 之後， 只需顯示感測器的 PIN (IO2)，不需顯示開關的 PIN (RX)。
> 若類型選擇 `開關` 、`檢查開關狀態`，只需顯示開關的 PIN (RX)

這個修好囉

**Comment by miterfrants** [comment]
> 測試 pipeline head 為感應器，設定完後發現沒有正常運作，比對資料後發現 FirstPieplineItemType = 0 (SCHEDULE) MyDevicePinSensorController.cs 行 70，撈出來的資料為空，所以 pipeline 沒有正常運作
> 
> 另外程式中找不到 firstPipelineItemType、firstPipelineItemDeviceId 是在哪個時候被更新的，猜測後面都用 PipelineHelper.GetHead 捉 Head 的 PipelineItemType、PipelineItemDeviceId，就沒有在用 firstPipelineItemType、firstPipelineItemDeviceId 了。
> 
> <img alt="截圖 2023-03-03 下午4 36 02" width="1055" src="https://user-images.githubusercontent.com/9404692/222671908-a30cff4b-b350-4915-be07-be9d14f30cab.png">
> 
> <img alt="截圖 2023-03-03 下午4 36 50" width="996" src="https://user-images.githubusercontent.com/9404692/222672076-a3765588-93d6-4849-be5a-55974913de3d.png">

這個修好囉

**Comment by miterfrants** [comment]
> 

fixed

**Comment by miterfrants** [comment]
> pipeline 在運行的時候，應該不能修改 item 的內容，避免資料為空值的時候產生錯誤。 要在非運行狀態的時候，才能修改 item 的內容。
> 
> <img alt="截圖 2023-03-03 下午2 14 52" width="757" src="https://user-images.githubusercontent.com/9404692/222645719-f1fc6359-f155-467e-b6dc-f7389365a1b4.png">

這個修好囉

**Comment by miterfrants** [comment]
> 移除名稱旁的 false <img alt="截圖 2023-03-03 下午1 50 01" width="884" src="https://user-images.githubusercontent.com/9404692/222650856-9f5f9a87-a2c3-4673-a5cc-468ae3d918b7.png">

修好囉

**Comment by miterfrants** [comment]
> `編輯 Pipeline `時，類型選擇 `感測器` 之後， 只需顯示感測器的 PIN (IO2)，不需顯示開關的 PIN (RX)。 若類型選擇 `開關` 、`檢查開關狀態`，只需顯示開關的 PIN (RX)
> 
> <img alt="截圖 2023-03-03 下午1 57 30" width="501" src="https://user-images.githubusercontent.com/9404692/222642853-4649c87a-43af-41eb-b943-3759c440b352.png">
> 
> <img alt="截圖 2023-03-03 下午1 58 35" width="515" src="https://user-images.githubusercontent.com/9404692/222643042-263ff54c-9fac-4076-b2db-f4a69d714989.png">

fixed

**Comment by miterfrants** [comment]
> 至 `編輯 Pipeline` 時，connectors 的線，只顯示開頭的 item 連到的下一個 item 的線，其餘的沒顯示，已確認 API 有正常拿到資料
> 
> 操作影片: https://user-images.githubusercontent.com/9404692/222641275-b7640740-365a-4e9a-91a6-d26fee32a725.mp4

這個應該是你之前加的，刪除 node 的時候沒有刪掉相關的 connection
