### ISSUE TITLE
Dashboard - 斷線通知

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1068]
# Why

可以第一時間知道裝置斷線，避免裝置很久沒有工作了還不知道

# Task

- [x] API Device 下線通知對象, 啟用下線通知欄位
- [x] API 下線通知前會檢查使用者是否為付費會員, 並檢查裝置是否啟用下線通知欄位
- [x] Dashboard 列表加上切換裝置是否啟用離線通知功能, 啟用時會跳出 dialog 填入 `下線通知對象` 可以填入 email 或是 多組電話
- [x] Dashboard 啟用離線通知功能，如果為免費會員跳出訂閱服務的功能

# Check List

- [ ] 檢查以上功能是否正常運作
