### ISSUE TITLE
Dashboard - Switch 和 Sensor API 都會 Trigger Device Online 

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1079]
# Why

- 因為有時候 Sensor 要送太多個 PIN, 導致距離下次再打 Online API 太久, 造成以為 Device 下線

# Task

- [x] API 在檢查 Switch Status 的時候多執行 `DeviceStateHelper.Create(_dbContext, _dbConnectionString, ownerId, id);` 
- [x] API 在送 Sensor 資料的時候多執行 `DeviceStateHelper.Create(_dbContext, _dbConnectionString, ownerId, id);` 

# Check List

- [ ] 檢查以上 Task 是否都有完成
