### ISSUE TITLE
Dashboard - 建立 React Dashboard App

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#112]
# Why

把 IoT 裝置 State 管理介面化

# Task

- [x] 建立 Dashboard  App
- [x] 撰寫 Routing Spec

# Check List

- [x] 一份寫好 Routing Rule Spec 的 Paper 
  - [x] Device List
  - [x] Device Pin State
  - [x] Device Pin Data
  - [x] Triggers
  - [x] Trigger Item
  - [x] oAuth Clients

- [x] Repo 加上 Dashboard React App

**Comment by miterfrants** [comment]
# Routes Spec
https://paper.dropbox.com/doc/Dashboard-Routes--BYBQ9adnfqljg8TWmh5ZjbxEAg-r8Ir0nYz7osOzWLI8h8OK
