### ISSUE TITLE
Firmware - refactor particle photon HTTP firmware

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1132]
# Why

particle photon HTTP 會在主機掛了以後或是網路斷線後後就卡住，沒有做重新連線的機制

# Task

- [ ] Refactor Code
- [ ] 確認斷線是否有重連機制
- [ ] 確認 Token 過期是否會重新連線
- [ ] 確認 Api Server 掛了以後是否會重新連線
- [ ] 長時間測試

# Check List

- [ ] 確認上方 Task 是否完成
