### ISSUE TITLE
Dashboard - 把 Trigger 拔掉

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1153]
# Why
Trigger 和 Pipeline 功能有點重複，統一用 Pipeline 取代掉

# Task

- [ ] API 把 Trigger 拿掉
- [ ] Dashboard 把 Trigger 拿掉
- [ ] Website 把 Trigger 拿掉並用 Pipeline 取代

# Check List

- [ ] 檢查以上 Task 是否完成

**Comment by miterfrants** [comment]
Pipeline Icon 換成現在的 Trigger Icon
