### ISSUE TITLE
Other - 研究 open source licence

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#116]
# Why
- 未來可能可以用 open source policy 來達到宣傳的效果

# Task
- [ ] 研究 open source policy 規範

# Check List
- [ ] 整理出 open source policy 規範
- [ ] 建議我們採用的 policy 規範

**Comment by miterfrants** [comment]
目前沒有要，等到要做再開起來
