### ISSUE TITLE
R&D - 植物疾病 AI 辨識

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1172]
# Why

提供更完整農作相關服務 e.g: 疾病辨識、缺肥辨識，可以把整個服務的生態鍊更完善。

# Task

- [ ] 研究在 GitHub 現有 Repo，並整理一份文件能說明我們可以怎麼選擇。
- [ ] 架設測試主機或是提供測試 ML 的文件
- [ ] 提供下一步我們該如何規劃這個 Plat Disease Recognize System API 

# Check List

- [ ] 檢查是否有產出這些文件
