### ISSUE TITLE
Website - Disable 關於我們、隱私權條款 pages

### ISSUE THREAD

**Issue by LiangYingC** [miterfrants/itemhub#119]
# Why

- 問題：目前的「關於我們」以及「隱私權條款」頁面空白，看起來不佳。
- 解法：不如先拔掉，不要讓人覺得施工到一半就上，拔掉會減少詐騙感，等之後頁面內容寫完，再打開即可。

# Task

- [x] 將 Footer 的「關於我們」以及「隱私權條款」註解掉
- [x] 將 「關於我們」以及「隱私權條款」的 route 註解掉

# Check List

- [ ] 確認外部無法進入「關於我們」以及「隱私權條款」頁面
