### ISSUE TITLE
Dashboard - 增加不同類型的 PIN

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1210]
# Why

目前沒有辦法處理以下幾種狀況
- PIN 類比輸出，控制像是可變電阻之類多段式調整電燈亮度
- 單一指令，對應像是紅外線 LED 送出把冷氣切到除濕指令，就不會像是 switch button 是開關這種相反意象的功能
- 類比監控，有最高最低值，可以讓初次看這個表就知道這個溫度有危害

# Task

- [ ] Dashboard 加上 Pin Type
  - [ ] analogy write
  - [ ] button & code block
- [ ] Monitor 加上新的類型
  - [ ] analogy monitor for sensor
  - [ ] button 
  - [ ] progress bar for sensor
  - [ ] progress bar for analogy write
- [ ] Firmware
  - [ ] analogy write
  - [ ] button

# Check List

- [ ] 檢查以上類型都有正常顯示在 Pin 腳
- [ ] 檢查 dashboard monitor 有新的四種類型
- [ ] 檢查 firmware 有針對新的兩種腳會生成不一樣的程式碼
