### ISSUE TITLE
Dashboard - 加上上傳圖片的 API

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1242]
# Why
每個 device 提供一個這樣的 channel, 讓使用者可以把監視畫面上傳到 ItemHub

# Task

- [x] API 新增可以上傳 Device Image 每一個 Device 只能有一個上傳圖片的接口
- [x] Dashboard 加上一個會一直更新圖片的 popup 

# Check List

- [ ] 檢查 staging server 是否以上功能
