### ISSUE TITLE
Dashboard - 加上檢查上線狀態的 Pipeline Item Type

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1245]
# Why

某一些裝置是長時間休眠，如果用下線通知會沒辦法確保這類型裝置是否正常運作

# Task

- [x] API 加上 Check Last Activity Log 
- [x] Dashboard 加上 `檢查最後一次上線時間`  Pipeline Item Type 

# Check List

- [ ] 確認以上工能有在 staging server
