### ISSUE TITLE
Website - Optimize Process of Starting Development

### ISSUE THREAD

**Issue by LiangYingC** [miterfrants/itemhub#125]
# Why

1. 目前啟動開發環境比較不直覺要自己下指令，因此寫成 script 後會更簡便。
2. 過程中會優化 server.js console.log() 的結果，直接印出開發環境全網址。
3. 試著做做看 hot reload.

# Task

- [x] Add npm run dev script
- [x] Add console.log('Sever Launch: https://dev.itemhub.io:443') on server.js
- [x] Implement hot reload

# Check List

- [x] Run npm run dev to open development environment
- [x] Will console.log('Sever Launch: https://dev.itemhub.io:443')
- [x] Will reload page after changing file

**Comment by LiangYingC** [comment]
先前沒做延宕，預計這週五（01/21）前會發 PR
