### ISSUE TITLE
R&D - 把 Matter  導入 ESP32 並可以在後台勾選是否要包含 Matter 

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1256]
# Why

- 增加應用場景
- 避免在沒有網路的情況下無法使用裝置

# Task

- [ ] 研究 Matter 怎麼導入 ESP32
- [ ] 測試燒錄
- [ ] 撰寫 firmware 
- [ ] Dashboard 加上 Matter checkbox

# Check List

- [ ] 檢查 homo 主機 esp32 mcu 是否有 matter firmware 可供使用

**Comment by miterfrants** [comment]
![S__8175619](https://github.com/miterfrants/itemhub/assets/2028693/06f33658-9262-4f2d-a938-b247eb4b0405)
