### ISSUE TITLE
Research - IoT 碳排放監控可行性

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#1259]
# Why

- [ ] 若是能做 IOT 碳排放監控，可以讓廠商實際應用我們的服務，或是可以與其他廠商談策略聯盟

# Task

- [ ] 訪查目前是如何做 iot 監控碳排放

# Goal

- [ ] 確認 IoT 碳排放監控可行性

# Report

- [ ] 可行性報告
