### ISSUE TITLE
API - 實作 Group 機制 

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1275]
# Why

讓第三方廠商有方式拉不同的人進到群組裡控制自己新增的裝置，豐富使用場景讓想做 IoT 硬體廠商有這個功能和更多動機來使用平台。

# 邀請流程
- 使用者在後台建立自己的 Group，只個建立人才看得到
- 使用者可以在 Group 內頁透過 Email 邀請人加入到這個 Group，邀請後會建立一個 Invitation 的資料
- 等到對方在平台上建立會員後會把 Invitation 刪除，並建立一個 RelationOfGroupAndUser 的資料

# 登入權限
- 登入時候會把 RelationOfGroup 的 role 塞到使用者 token 中 roles 裡頭
- 使用者介面會增加一個下拉選單，讓他要顯示哪些裝置，這個資料會記載在 cookie 裏頭，並在打 API 的時候丟到參數裡頭
  - 只有自己的裝置 `SELF`
  - 群組名稱 `GROUP_FILTER=["group id 1", "group id 2"]`
  - 混合顯示  `MIX`

# Task

## Group 機制
  - [x] CRUD 群組 API，新增好的 GROUP 會有一個 Roles `["group_{group_id}"]`
  - [ ] Dashboard 加上 Group CRUD 的功能，如果這個 Group  底下有設定的使用者和裝置會跳出第二次的提醒確認是否要刪除
  - [x] 邀請使用者加入 Group
  - [x] Group's Users
  - [x] Group's Devices

## Group Token
  - [x] 交換 Dashboard Token 時把拿到授權群組 roles

## 後台
  - [x] 後台群組裝置列表
  - [x] 後台 Dashboard
  - [x] 後台加上切換成群組模式

## API
- [x] 實作 IotGroupAuthorizeFactory, IotGroupAuthorizeAttribute
- [x] 裝置相關的 api 允許相同 Group 的人 access
  - [x]  `GET` `v1/group/{groupId}/devices`
  - [x]  `GET` `v1/group/{groupId}/devices/{id}` -> 目前不需要這個了
  - [x]  `GET` `v1/group/{groupId}/devices/{id}/last-activity`
  - [x]  `GET` `v1/group/{groupId}/devices/{id}/read-last-file`
  - [x]  `GET` `v1/group/{groupId}/read-last-file-thumbnail`
  - [x]  `GET` `v1/group/{groupId}/pins`
  - [x]  `GET` `v1/group/{groupId}/pins/{pin}`
  - [x]  `GET` `v1/group/{groupId}/pins/sensors/{pin}`
  - [x]  `GET` `v1/group/{groupId}/pins/sensors/{pin}/aggregate`
  - [x]  `GET` `v1/group/{groupId}/pins/switches` -> 目前不需要這個了
  - [x]  `PATCH` `v1/group/{groupId}/switches/{pin}`
  - [x] `GET` `v1/group/{groupId}/dashboard-monitors` -> 目前不需要這個了
  - [x] `POST` `v1/group/{groupId}/dashboard-monitors` -> 目前不需要這個了
  - [x] `PATCH` `v1/group/{groupId}/dashboard-monitors/sorting` -> 目前不需要這個了
  - [x] `PATCH` `v1/group/{groupId}/dashboard-monitors/{id}` -> 目前不需要這個了
  - [x] `DELETE` `v1/group/{groupId}/dashboard-monitors` -> 目前不需要這個了

# Check List

- 確認已上 API 都能正常回應
- 使用非群組帳號，打以上 API 應該要收到 Forbidden 的回應
