### ISSUE TITLE
Dashboard - 優化 AutoComplete Search 

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1339]
# Why

- 目前輸入完以後要自己手動清掉 input 才有辦法清除再新增

# Task

- [x] 加上可以自動清除 input 的 flag 給 parent component 操作
- [x] 修改所有有使用到 auto complete 的 parent component

# Check List

- [x] my-group-devices.tsx
- [x] device-and-pin-input.tsx
- [x] offline-pipeline.tsx
- [x] check-last-online-pipeline-item.tsx
