### ISSUE TITLE
Dashboard - Computed Sensor Data

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1341]
# Why
讓 Sensor 資料可以經過加工或是加上其他裝置的資料顯示在 Line Chart, Current Value

# Task

- [x] Sensor 加上設定按鈕
<img width="960" alt="截圖 2023-08-02 上午12 43 19" src="https://github.com/miterfrants/itemhub/assets/2028693/169e02b9-6ebe-445e-b6d1-f70e2325f597">

- [x] 加上 Computed Function 和 選取裝置 PIN
- [x] Dashboard Sensor Monitor 加上 Computed Function 

# Check List

- [ ] 測試 Sensor Raw Data 可以經過另外 Sensor Pin 的值經過特定公式轉換成別的數值
