### ISSUE TITLE
Website - 撰寫 Website 剩下頁面的 Spec

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#135]
# Why
把 Website 剩下註冊, 登入, 忘記密碼功能補齊

# Task
- [x] 註冊
- [x] 登入
- [x] 忘記密碼
- [x] 隱私權條款
- [x] Detail of How to use
- [x] Detail of Pricing (這個 depend on 定價評估)
- [ ] 關於我們

# Check List
- [ ]  產出一份 Spec Paper
- [ ] 開啟對應的 Issue

# Dependency
- #147

**Comment by miterfrants** [comment]
登入相關的都會在這邊處理, 所以如果使用者要跳到 dashboard 前會先檢查有沒有兩階段驗證
驗證完拿到 token 才會進到 dashboard

**Comment by vickychou99** [comment]
- 註冊、登入、忘記密碼，已經有設計稿了，所以不用寫
- 關於我們等之後有機會要找人還幹嘛的，再來寫
- 加寫兩步驟驗證

**Comment by vickychou99** [comment]
https://paper.dropbox.com/doc/ItemHub-Website-Spec--BZoL9MOMjVHheUTPjfzvLf5aAg-3MswyjbQWdjOqIOjUieNz

**Comment by miterfrants** [comment]
已經在 Paper Spec 上面留言囉!
然後把現有產出的 issue 都拉到第二個 milestone 
完成 dashboard
