### ISSUE TITLE
Operation - 更換測試機的 IP

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1370]
# Why 

Github 上面有洩漏 dbc 

# Task

- [x] OpenVPN 重新 Generate Profile 
- [x] TablePlus 修改連線 IP
- [x] Homo 底下所有網站更換 DBC

# Goal

- [ ] 無斷線的更換測試機 IP
