### ISSUE TITLE
Feature - log pipeline type 取代 execute log 給使用者看

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1410]
# Why

現在 execute log 看不太懂到底是什麼狀況，還不如讓使用者自定義 log 看要在什麼狀態下新增 log 來記錄執行到哪一個階段停下來，Pipleine Execute Log 給開發者看就好。

# Task

- [x] Log Model 加上 Type field, Common Log, Pipeline Log
- [x] 實作 Log Pipeline Type Logic
- [x] Implement get pagination Log API Controller
- [x] F2E 把 Pipeline Execute Log 改成 Log 
- [x] 清除超過三天的 pipeline log

# Check List

- [x] Pipeline Log 是否由本來打 `/api/v1/my/pipeline-execute-logs/` 改為 `/api/v1/my/logs?type=1`
