### ISSUE TITLE
Operation - 溫室 LED 燈條改造

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1425]
# Why 

改造溫室燈條，可讓日後規模化的時候可以快速切換，或是日後 LED 燈老化維修更容易
計畫是利用現成的軌道燈當作電源軌道，並利用現成市面上的軌道電源把電源接在 LED 上面可以快速裝拆

# Task

- [ ] 購買軌道燈軌
- [ ] 購買軌道電源接頭
- [ ] 製作新的 LED 登板
- [ ] 改裝現有 LED 燈板 X 8
- [ ] 安裝軌道電源
- [ ] 安裝 LED 燈板

# Goal

- [ ] 

# Report

- [ ]
