### ISSUE TITLE
Dashboard - 允許連續數值的操作

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1426]
# Why

可以透過前台操作連續數值控制裝置 e.g: 馬達轉 15 圈，現在只能開和關

# Task

- [ ] API Device Pin Model 除了 SWITCH, SENSOR 再加上 CONTINUOUS_OPERATOR
- [ ] Dashboard 加上 Progress Bar 的控制器
- [ ] Dashboard Monitor 加上 Progress Bar 控制

# Check List

- [ ] 可在前台控制馬達轉幾圈或是反轉幾圈
