### ISSUE TITLE
Website - 定價評估

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#147]
# Why
- 確保毛利不會是負的, 越多人賠越多錢
- 希望第一階段每一位參與的人會有額外 NTD 5,000 收入補貼 (目前四個人加上成本大概 5000 * 4 * 1.5)

# Task

- [x] 成本評估
  - [x] 研究銀行或第三方支付訂閱付費的抽成比例
  - [x] Storage 費用
  - [x] Google Compute Engine 費用
  - [x] 資料庫備份 Storage 費用
- [x] 使用者數量的評估
- [x] 費用制定

# Check List
- [x] 提供一份定價 Paper 
- [x] 開啟接洽金流公司的 Issue
- [x] 開啟 Website - 文案修改的 Issue

**Comment by miterfrants** [comment]
https://cloud.google.com/products/calculator

**Comment by miterfrants** [comment]
定價 Paper
https://paper.dropbox.com/doc/Cost-Analytics-2q8wGr8m78Q0dMp7cLBZV#:uid=639332551225417317669512&h2=%E4%BA%BA%E4%BA%8B:-%2436%2C000
