### ISSUE TITLE
Operation - 申請金流服務 TapPay

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#151]
# Why
申請第三方金流服務可以讓之後工程師串接

# Task
- [ ] 申請第三方金流服務
- [x] 開啟 checkout page 頁面切版 issue
- [x] 開啟 checkout page 跟設計師溝通的 issue
- [x] 開啟 checkout page 串接工程 issue

# Check List
- [ ] 取得 API 文件和特店號碼
- [ ] checkout page 頁面切版 issue
- [ ] checkout page 跟設計師溝通的 issue
- [ ] checkout page 串接第三方金流的 issue

# Dependency
- #147

**Comment by vickychou99** [comment]
API 文件:
https://github.com/TapPay/tappay-web-example/tree/master/Payment_Request

**Comment by miterfrants** [comment]
這個壓 2/6 號也太不合理了吧？

**Comment by vickychou99** [comment]
等 tappay 回信收單帳號

**Comment by vickychou99** [comment]
合約已用印並寄出，待對方用印

**Comment by vickychou99** [comment]
收單銀行帳號合約文件確認中
