### ISSUE TITLE
Dashboard - 研究流行的 Microcontrol Chip 並歸納哪些程式碼應該變成自動產生

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#159]
# Why
歸納出這些晶片可以共用哪些 code

# Task

- [x] 實作 Arduino Nano 3 IoT  濕度感測器
- [x] 實作 ESP8266 濕度感測器
- [x] 實作 Particl Io Photon 濕度感測器
- [x] 優化 Code 變成可以透過 Auto Generate 

# Check List

- [x] 產出三個專案 Project, 並可在實際的裝置上面運作
- [x] 產出 Auto Generate Issue

**Comment by miterfrants** [comment]
目前 arduino 33 IoT 會送一段時間就掛了目前正在排除問題
raspberry pi pico 需要額外掛 ESP-01S, 已經買了 USB 轉 UART 等來了再來刷 ESP-01S fireware

**Comment by miterfrants** [comment]
arduino 33 IoT 因為 wifi nina SPI driver 送一段時間就會有問題, 所以就直接把晶片重開

**Comment by miterfrants** [comment]
ESP-01S 看起來記憶體不太夠沒辦法設定 token

**Comment by miterfrants** [comment]
- 先來修一下 particle io photon 會定時斷線的問題

**Comment by miterfrants** [comment]
particle io 只送 status 可以從 3:04 - 11:00

**Comment by miterfrants** [comment]
- 先來修一下 particle io photon 會定時斷線的問題
- arduino nano 33 IoT wifi nina SPI Driver 會一段時間就送不出 request 的問題

**Comment by miterfrants** [comment]
驗收的時候可以檢查三個資料夾
https://github.com/miterfrants/itemhub/tree/dev/firmware/arduino-nano-33-iot
https://github.com/miterfrants/itemhub/tree/dev/firmware/esp-01s
https://github.com/miterfrants/itemhub/tree/dev/firmware/particle-io-photon

是否資料夾底下有相對應得 `.info` 檔案
e.g: esp-01s 資料夾底下有沒有 esp-01s.info

另外是可以在正式機登入 Peter 的帳號可以看到

## ESP-01S
<img width="651" alt="截圖 2022-04-21 下午1 34 28" src="https://user-images.githubusercontent.com/2028693/164381529-480eb351-2ef5-41eb-a9f7-56042a7aec67.png"> 

## Arduino Nano 33 IoT
<img width="652" alt="截圖 2022-04-21 下午1 35 03" src="https://user-images.githubusercontent.com/2028693/164381587-c25efc62-c48c-41dc-919b-152da6c58f5e.png">

## Particle Photon
<img width="655" alt="截圖 2022-04-21 下午1 35 34" src="https://user-images.githubusercontent.com/2028693/164381641-d71f0b39-f86e-49d1-818d-4716982cfbe2.png">
