### ISSUE TITLE
Dashboard -  實作 Device Offline State 

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#184]
# Why
- 目前沒有實作 Device Offline 機制, 所以資料庫 online 是 true 就永遠都是 true, 需要一個特定的機制, 當 device 一段時間沒有送 request 來時, 會把 online 切成 false

# Task

- [x] 實作 scheduled update record in database (避免使用 Database 的機制, 盡量寫在 Application Layer, Scale 比較不會遇到設定問題)
- [x] 之前沒有想清楚在 DeviceState 改名為 DevicePinState
- [x] DB DeviceState.Online 移除
- [x] DB DevicePinData.Online 移除
- [x] DB Device 加上 Online 欄位
- [x] 在取得 DevicePinState 的同時去重設定時器 -> 改由獨立的 api 處理 `/devices/:id/online`
- [x] 在送出 DevicePinData 的時候重設定時器 -> 改由獨立的 api 處理 `/devices/:id/online`

# Check List

- [x] 請 Peter 把他手邊的裝置關掉, 看一下 Device.Online 是否有被更新成 Offline
