### ISSUE TITLE
Dashboard - 實作 Devices 列表

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#199]
# Why
完成第二個 Milestone, 其中必要的條件 

# Task

- [ ] 串接 Devices API (參考 API  https://github.com/miterfrants/itemhub/blob/master/api/Controllers/MyDeviceController.cs)
- [ ] 在頁面顯示 Device 列表, 列表包含名稱(Name) ,是否上線(Online), 裝置 ID (DeviceId)

# Check List

- [ ] 確認使用 Peter 帳號登入後, 能取得三個裝置
- [ ] 檢查是否列表上有顯示上面三欄

**Comment by LiangYingC** [comment]
@miterfrants 問個

需要把接到的資料送進 redux store 嗎？

抑或是這個 issue 目標先聚焦接上 API，讓畫面跑出來為先？

**Comment by LiangYingC** [comment]
有看到在  app.tsx ` const devices = useSelector(selectDevices);` ，應該是要塞進 redux store 中

**Comment by miterfrants** [comment]
對喔, 要用 redux

**Comment by LiangYingC** [comment]
收到 thx
