### ISSUE TITLE
Dashboard - optimize react development exprience

### ISSUE THREAD

**Issue by LiangYingC** [miterfrants/itemhub#206]
# Why

趁著尚未密集開發功能前，先優化調整小項目，優化開發體驗，但不影響功能

- 拔掉 import React
- compoment 資料夾和檔案名稱統一小寫
- alias: https://dev.to/larswaechter/path-aliases-with-typescript-in-nodejs-4353

其他做的過程中想到的小優化。

# Task

- [x] Remove import React
- [x] Uniform component files capitalization 
- [x] TS alias

# Check List

- [ ] No see import React
- [ ] All component files are lowercase
- [ ] Use ts alias path
