### ISSUE TITLE
Dashboard - 在正式環境把 Dashboard 架起來

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#207]
# Why
完成第二階段 Milestone, 完成 Dashboard 

# Task

- [x] 修改 Deploy Shell Script 
- [x] 修改 nginx config

# Check List

- [x] 確認 https://itemhub.io/dashboard 可以看到 react app
- [x] 沒有登入的狀態會被導會 https://itemhub.io

**Comment by vickychou99** [comment]
https://itemhub.io/dasshboard 可以看到 react app
 >> 404

**Comment by miterfrants** [comment]
Dashboard
