### ISSUE TITLE
Dashboard - make sure eslint and prettier work on all coworkers development

### ISSUE THREAD

**Issue by LiangYingC** [miterfrants/itemhub#214]
# Why

1. 目前 prettier 啟動與否會吃每位開發者自己 vscode / 本機環境的設定，每個人的設定不同就會有問題。
2. 目前 ts x eslint x prettier 的設定有點問題，導致其實 lint error 很多，但沒被自動 format or 報錯。
3. 目前尚未有 react-hook 相關的 eslint 規則，需要安裝會比較安全。

![截圖 2022-01-23 下午3 12 22](https://user-images.githubusercontent.com/56446970/150668755-fca839c4-12ab-4ab7-8b5c-5fae70e6561e.png)

# Task
- [x] install prettier and related plugin on project
- [x] install react / react hook plugin on project
- [x] adjust eslintrc.json to make sure lint is correctly work.
- [x] create eslintignore
- [x] fix lint / format error

# Check List
- [x] Run `npm run lint` and no error result
- [x] Can format on save
