### ISSUE TITLE
Dashboard - 實作 Device 頁面 API 串接

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#224]
# Why
https://github.com/miterfrants/itemhub/milestone/2

# Task

- [x] 在頁面顯示 Device 資訊, 包含名稱可編輯(Name) ,是否上線(Online), 裝置 ID (DeviceId) 串接 `GET` `/v1/me/devices/{id}` API (參考 API server swagger https://dev.itemhub.io:5001/swagger/index.html), 如果列表已經有資料就從 redux 拿.
- [x] 名稱可以編輯, 串接 `PATCH` `/v1/me/devices/{id}` API (參考 API server swagger https://dev.itemhub.io:5001/swagger/index.html)
- [x] Device 基本資料下方有 Pin List 串接 `GET`  `/api/v1/me/devices/{id}/pins` 

# Check List

- [x] 檢查從 `/dashboard/devices/ ` 頁面到  `/dashboard/devices/{id}` 頁面是否有顯示上方資訊
- [x] 檢查 `/dashboard/devices/{id}` 頁面，按下瀏覽器的 reload 後，是否有顯示上方資訊

# Dependency
#225
