### ISSUE TITLE
DevOps - 建立 Itemhub Production Server

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#236]
# Why

![This is an image](https://mermaid.ink/svg/pako:eNp90cGKgzAQBuBXGeaUQnvZo4cFbWzrnhZa6CWX0cyuUk1KjAul9N0brYLLsuYU_vnCT5I7FlYzRvjt6FrCSSoDYcWitqQhp5pMwW4Fm807JOLMORzZ_bCDeLUgt3OZjDIZRlLEn9k0ygxIW1zCsTlJhaS2zMk6Dbu3dMS_yK4vaCvPf8F2APulmhc5LNW8SPZ_zX4AH0JO15PzoI9wjQ27hiodnvfeJwp9yQ0rjMJWk7soVOYRXHfV5DnVlbcOoy-qW14jdd4eb6bAyLuOJyQrCl_VjOrxBKYGg4s)

-  避免 github 直接 auto deploy to production 造成 api server 會在 merge 後一段時間不能使用, devices 會出現 api error

# Task

- [x] 架設 load balancer 避免 api server 在 deploy 期間無法使用
- [x] DB 改用 GCP SQL
- [x] 處理 TSL in load balancer
- [x] 把 staging server 降低一個 level 省錢
- [x] DNS 指定到 load balancer
- [x] Line Bot Build And Deploy Production
  - [x] 加上 Web Deployment 加上 Line Bot
  - [x] Web Deployment Itemhub Repo 可以有兩個 Branch 一個是 dev 一個是 master, merge to dev 的時候會在 staging server 跑 deploy 流程 merge master 不會有反應
  - [x] Line Bot Build for Production
  - [x] Line Bot Deploy Production
- [x] 把目前的服務切成三個 instance group
  - [x] Website 一台 web server (GCE G1 Micro)
  - [x] Dashboard 一台 web server (GCE G1 Micro)
  - [x] API 三台 web server (GCE E2 Medium)

# Check List

- [x] 透過 Line Bot deploy, 並且打 api server 不會有停止服務的狀況, 可以透過 `https://itemhub.io/api/v1/test` 來確認是否有停止

**Comment by miterfrants** [comment]
加上 Auto Deploy Task

**Comment by miterfrants** [comment]
<img width="1180" alt="截圖 2022-03-05 下午4 27 46" src="https://user-images.githubusercontent.com/2028693/156875307-1da61e25-1bd9-4593-820c-b766aafa013a.png">
<img width="582" alt="截圖 2022-03-05 下午4 28 14" src="https://user-images.githubusercontent.com/2028693/156875310-f0e850d0-bfff-4ca7-9c69-948f39bf20b8.png">

**Comment by miterfrants** [comment]
api server 目前改成兩台, 如果他的 connection 超過 2000 * 0.85 會自己往上開
