### ISSUE TITLE
API - 實作 Device Pin State/Data WebSocket 

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#237]
# Why
client 端可以及時取得 device pin 目前的狀態或是資料 (讓有即時需求的使用者可以透過這個 API 立刻取得狀態是否更新, 可作為進階使用者收費的吸力)

# Task

- [ ] 實作 WebSocketPool 機制
- [ ] 實作 WebSocket Endpoint 讓 client 端可以串接資料
- [ ] 實作 WebSocket Push Message 時機和機制

# Check List

- [ ] 用 Peter 帳號登入後看一下 Device Id 60 PIN D2 是否有大約每 30 秒就收到一次 ws 來的資料

**Comment by miterfrants** [comment]
目前沒有要，等到要做再開起來
