### ISSUE TITLE
Dashboard - 整合好所有 API 錯誤時，對應跳出的錯誤訊息

### ISSUE THREAD

**Issue by LiangYingC** [miterfrants/itemhub#241]
# Why

1. 目前 API 錯誤的處理，並尚未有良好的統整，之後串接錯誤會比較麻煩 => 期許處理完畢後，可以有整合好的 config 填入對應各種錯誤 https status code 而回傳的訊息或畫面。
2. 目前 reponse data / error 都沒有明確的 ts type 規範，僅有 any => 需要有 type 規範，讓程式碼更安全，避免開發者以為有 ts 保護，但事實上並沒有。

# Task

- [x] 重構與加上 reponse data type
- [x] 重構與加上 reponse error type
- [x] 將錯誤處理邏輯，彙整管理好，未來有彙整處可對應 client 跳出錯誤訊息 => 目前彙整處會在 `useFetchApi`  中，`catch error` 之處

# Check List

- [x] 收到 API 錯誤時，跳出對應的彈窗，如附圖概念（未來不一定是彈窗，但現在可以先簡單做成彈窗，重點是先實作彙整錯誤的邏輯）

<img width="661" alt="截圖 2022-02-13 下午11 05 37" src="https://user-images.githubusercontent.com/56446970/154100658-437ab7e0-3bf8-4ef7-a933-9330d2b70ba5.png">

**Comment by miterfrants** [comment]
這個會是寫一個 hook 嗎？
useErrorHandler 這樣
然後所有 useXXXApi 都會在裡頭呼叫 useErrrorHandler 
不知道我的想像對嗎？

**Comment by LiangYingC** [comment]
> 這個會是寫一個 hook 嗎？ useErrorHandler 這樣 然後所有 useXXXApi 都會在裡頭呼叫 useErrrorHandler 不知道我的想像對嗎？

不太對，不打算在「所有 useXXXApi 都會在裡頭呼叫 useErrrorHandler」這樣不太好維護，因為錯誤處理這件事情，應該會是全 dashboard 統一，例如遇到 403，就跳出 403 用的彈窗給顧客。

理想的情況下，最後會是在 useFetch 那隻 hook 中 cache error，然後對應 error code 返回對應的處理畫面或邏輯。

**Comment by LiangYingC** [comment]
> > 這個會是寫一個 hook 嗎？ useErrorHandler 這樣 然後所有 useXXXApi 都會在裡頭呼叫 useErrrorHandler 不知道我的想像對嗎？
> 
> 不太對，不打算在「所有 useXXXApi 都會在裡頭呼叫 useErrrorHandler」這樣不太好維護，因為錯誤處理這件事情，應該會是全 dashboard 統一，例如遇到 403，就跳出 403 用的彈窗給顧客。
> 
> 理想的情況下，最後會是在 useFetch 那隻 hook 中 cache error，然後對應 error code 返回對應的處理畫面或邏輯。

```
......

export const useFetchApi = <T>({
    initialData,
    fetchMethod,
    callbackFunc,
}: {
    initialData: T | null;
    fetchMethod: () => Promise<T>;
    callbackFunc?: (data: T) => void;
}) => {
    const [data, setData] = useState<T | null>(initialData);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState(null);

    const fetchApi = useCallback(async () => {
        if (isLoading) return;

        try {
            setIsLoading(true);

            const data: T = await fetchMethod();
            if (callbackFunc) {
                callbackFunc(data);
            }

            setData(data);
        } catch (err: any) {
            // 將錯誤處理邏輯整合於此，目前僅是舉例說明概念，實作細節可能有所差異。
            errorData = ERR_DATA_CONFIG[err.code] // 從 config 中取出對應要處理的資訊。
            dispatch(XXX)  // 會將 error 傳進去 Errol modal redux store，藉此跳出對應的 Error Modal 彈窗
        } finally {
            setIsLoading(false);
        }
    }, [isLoading, fetchMethod, callbackFunc]);

   ......
};
```
