### ISSUE TITLE
Dashboard - Trigger 列表頁面和單一頁面 CRUD

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#248]
# Why
https://github.com/miterfrants/itemhub/milestone/2

# Reference
- 詳情請參考 Swagger Trigger Section 目前為實作

# Task

- [x] Trigger 列表具有分頁
- [x] Trigger 列表會顯示, `來源裝置名稱`, `來源裝置 PIN` , `目標裝置名稱`, `目標裝置 PIN`, `Operation`, `門檻` 
- [x] Trigger 列表頁可以做批次刪除, 刪除前會跳出提醒避免使用者誤刪, 可以參考 github remove repo 的作法輸入 repo name 或是輸入 DELETE
- [x] Trigger 列表有搜尋功能可依照 `來源裝置` 或是 `目標裝置` 來做過濾
- [x] Trigger 內頁可對 `來源裝置`, `來源裝置 PIN` , `目標裝置`, `目標裝置 PIN`, `Operation`, `門檻`  做修改
- [x] Trigger 內頁的 `來源裝置`, `目標裝置` 是一個 AutoComplete 的 Text Input 輸入文字時會搜尋使用者當前有的裝置列表, 有值得情況下才能選擇各自的 PIN ex: <img width="391" alt="截圖 2022-02-12 上午5 16 19" src="https://user-images.githubusercontent.com/2028693/153671354-f9376275-0831-4c48-b1cb-65c618c5d8e6.png">
- [x] Trigger 內頁的 `Operation`  為一個下拉選單包含 `>`, `<`, `>=`, `<=`, `=` 五種, 資料來源可以參考 `/api/v1/universal/trigger-operation` 目前未實作  #249 
- [x] Trigger 內頁的 `門檻` 是一個數字 (decimal) 輸入框
- [x] Trigger 內頁具有 CRUD 的功能

# Check List

- [ ] 檢查 Trigger 列表頁面是否符合以上的 Spec
- [ ] 檢查 Trigger CRUD 是否正常運作

# Dependency 
- #249 
- #250
