### ISSUE TITLE
API - Triggers

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#250]
# Why

https://github.com/miterfrants/itemhub/milestones

# Task

- [x] 實作 pagination list 包含 `來源裝置名稱`, `來源裝置 PIN` , `目標裝置名稱`, `目標裝置 PIN`, `Operator`, `門檻`, `來源 PIN 狀態`, `目標 PIN 狀態`
- [x] 實作 Patch Trigger 包含以上這些資料更新
- [x] 實作批次刪除 Trigger

# Check List

- [x] 檢查 CRUD 和 批次刪除是否符合以上規則
