### ISSUE TITLE
Dashboard - Firmware Auto-Generator

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#253]
# Why
https://github.com/miterfrants/itemhub/milestones

# Task

- [x] 新增資料表 FirmwareBundleLog
  - [x] 有以下欄位 OwnerId, BundleId, DeviceId
- [x] 產生打包檔案的 API (Lazy Bundle) 
  - [x] URL `/api/v1/devices/:id/bundle-firmware` `POST`
  - [x] 打包的同時會把舊的 oAuthClient 刪除產生新的
  - [x] 產生 BundleId 把它存在資料表中
  - [x] Response `{"bundle": "/api/v1/firmware/:bundleId"}`
  - [x] 啟動一個 Async Task 10mins 後刪除打包檔
- [x] 加上下載 firmware 的 API 
  - [x] URL `/api/v1/firmware/:bundleId` `GET`
  - [x] 下載前驗證身份確認 dashboardToken 中的 userId 和 bundle ownerId 相同

# Check List

- [ ] 驗證以上功能是否都正常運作
