### ISSUE TITLE
Website - 實作 兩步驟驗證

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#258]
# Why
讓 USER 可以兩步驟頁面登入

# Task

### 實作兩步驟登入
- [x] 至 dashoboard 時，檢查 cookie 內有無 website token 
    - [x] 若沒有 website token 則 redirect 至登入頁
    - [x] 若有 website token  檢查是否過期，若已過期，則刪除 website token 後 redirect 至登入頁
- [x] 確認 cookie 內有 website token 且未過期，檢查 cookie 有無 dashboard token
    - [x] 若沒有 dashboard token 需 redirect 至兩階段驗證頁
    - [x] 若有 dashboard token 檢查是否過期，若已過期，則刪除 dashboard token 後 redirect 至兩階段驗證頁 
    - [x] 若有 dashboard token 且未過期，則 redirect 至 dashboard 首頁
- [x] 至兩階段段驗證頁時
    - [x] 按鈕預設為”發送驗證碼”，點擊後發送有驗證碼的通知信至會員信箱，按鈕為 disable 的狀態並倒數 60 秒，文字切換為 “可於XX秒後重新發送”，倒數完後按鈕變 enabled，文字切回原本的”發送驗證碼”
    - [x] 輸入驗證碼失敗時，需顯示錯誤訊息
    - [x] 輸入驗證碼成功時，新增 dashboard jwt token 且過期時間為 72小時(3天)，並 redirect 至 dashboard 

# Check List

 - [ ] 確認依照 task 內容實作

# Dependency
- #161

**Comment by miterfrants** [comment]
什麼情況會進到兩階段驗證?

**Comment by vickychou99** [comment]
機制說明:
https://docs.google.com/presentation/d/1zdGotJl7VvfW0Y_SP-O3uzUo_m3v2nrL/edit#slide=id.g10ad0e378e9_0_103

**Comment by miterfrants** [comment]
可以的話把他都整理在 github 上面

**Comment by miterfrants** [comment]
> 機制說明:
> https://docs.google.com/presentation/d/1zdGotJl7VvfW0Y_SP-O3uzUo_m3v2nrL/edit#slide=id.g10ad0e378e9_0_103

這個還是沒有說明實作的機制

**Comment by vickychou99** [comment]
> > 機制說明:
> > https://docs.google.com/presentation/d/1zdGotJl7VvfW0Y_SP-O3uzUo_m3v2nrL/edit#slide=id.g10ad0e378e9_0_103
> 
> 這個還是沒有說明實作的機制

已補

**Comment by miterfrants** [comment]
> 請把他都整理在 github 上面, 避免上面那個連結不小心誤刪之類找不到

@vickychou99

**Comment by vickychou99** [comment]
> > 請把他都整理在 github 上面, 避免上面那個連結不小心誤刪之類找不到
> 
> @vickychou99

https://github.com/miterfrants/itemhub/pull/276/files
更新 readme

website spec 更新兩步驟驗證的 spec
https://paper.dropbox.com/doc/itemhub-Website-Spec--BcdhpeqX21J9~PBnmBgB55kbAg-3MswyjbQWdjOqIOjUieNz

**Comment by miterfrants** [comment]
把他 spec 列成一個個的 task

**Comment by vickychou99** [comment]
> 把他 spec 列成一個個的 task

DONE
