### ISSUE TITLE
Website - 實作 checkout 付款頁

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#272]
# Why
實作 checkout 付款頁

# Task

- [ ] 實作 checkout 付款頁

# Check List

- [ ] 確認 pricing 選擇訂閱方案後至 checkout 付款頁可顯示選擇的訂閱方案
- [ ] 確認於 checkout 付款頁可切換其他的訂閱方案

# Dependency
- #157 
- #257
