### ISSUE TITLE
Dashboard - Device CRUD

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#308]
# Why
https://github.com/miterfrants/itemhub/milestone/2

# Task

- [x] 建立裝置表單 (由 Device 建立)
- [x] 刪除裝置
- [x] 修改裝置名稱
- [x] 裝置列表加上是否上線欄位
- [x] 裝置列表加上 Switch PIN 的狀態
- [x] 裝置列表加上 Sensor PIN 最近一次的資料和建立的時間
- [x] 裝置內頁, PIN 修改名稱
- [x] 裝置內頁, 可觸發 Switch PIN 開關

# Check List

- [x] 檢查上方功能是否完整
