### ISSUE TITLE
API - 整理 Swagger UI 並公開到正式主機

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#322]
# Why
- https://github.com/miterfrants/itemhub/milestone/2
- 提供使用者可用的 API 文件

# Task

- [x] 優化 API 路徑, 避免 Auto Generated Swagger UI 繼承路徑的問題
- [x] 客製化文件說明內容
- [x] Devices CRUD Document
- [x] Triggers CRUD Document
- [x] OAuthClients CRUD Document

# Check List

- [x] Devices CRUD Document
- [x] Triggers CRUD Document
- [x] OAuthClients CRUD Document

**Comment by miterfrants** [comment]
https://itemhub.homo.tw/swagger/index.html
