### ISSUE TITLE
API - 把超過一天的 Device Activity Log 清掉

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#327]
# Why
https://github.com/miterfrants/itemhub/milestone/2

# Task

- [x] 建立一個 Cronjob Service 清除超過一天 Device Activity Log 

# Check List

- [x] 現開啟 Mysql Client 大量複製 DeviceActivityLog Table 的資料把這些資料的 CreatedAt 時間修改成 一天前
- [x] 把 Startup.cs Cronjob 的觸發時間改為每分鐘
- [x] 一分鐘後檢查 DeviceActivityLog 是否有被刪除

**Comment by vickychou99** [comment]
Cronjob 有執行但沒執行到 DoWork 那段
<img width="600" alt="截圖 2022-03-18 上午1 16 18" src="https://user-images.githubusercontent.com/9404692/158857279-3ac4b3f0-7c60-49d1-9464-5c4f007ac35f.png">
