### ISSUE TITLE
API - Trigger Log

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#328]
# Why
- https://github.com/miterfrants/itemhub/milestone/2
- 加上 Trigger Log 

# Task

- [x] 有觸發 Trigger 當下的資料記錄下來
- [x] 加上 Cronjob Service 把超過 30天的 Log 清除

# Check List

- [x] 先透過 Peter 的帳號登入, 取得 token, 再用這個 token 透過兩階段驗證, 換到 dashboardToken
- [x] 打 `/api/v1/me/devices/60/sensors/D2` `POST` `{"value": 60}` 檢查一下看 `TriggerLog` 資料表裡頭有沒有資料
- [ ] 把剛剛新增的 TriggerLog 的 CreatedAt 改成 30 天以前的時間
- [ ] 把 Startup.cs 改 Cronjob Service 每分鐘觸發, 看一下剛剛觸發的 TriggerLog 有沒有被刪除
