### ISSUE TITLE
DevOps - Release Convention 

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#417]
# Why
讓 Release 可以達到 CI/CD 的精神

# Task

- [ ] 自動化 Release Description (Semantic Release), 目前 Commit Message 都有 follow Semantic Release  Rule 所以應該是可以透過一些工具把這些 commit message 自動整理成 Release Descripotion
- [ ] 制定 Release 流程

# Check List

- [ ] 一套 Release 流程
- [ ] 會在 Line Bot 提醒大家現在當前 Release 的版本
