### ISSUE TITLE
Dashboard - Devices page unexpected auto fetch switches pin api

### ISSUE THREAD

**Issue by LiangYingC** [miterfrants/itemhub#419]
# Why

加資料時偶發性問題，在 Device page 中，當將新增一個 DevicePinSensor 設定為 mode = 1 , value = 0 時，

<img width="516" alt="截圖 2022-04-16 下午6 59 32" src="https://user-images.githubusercontent.com/56446970/163672588-93932a77-a8b8-40e2-8186-5bf2b697cd29.png">

會自己打 devices/{deviceId}/switches/{pinid} api，看起來是前端切換 `Pin` component `switch` 相關的寫法造成

```
const { isLoading: isChanging, updateDeviceSwitchPinApi } =
        useUpdateDeviceSwitchPinApi({
            deviceId,
            pin,
            value,
        });

   ......
    const toggleSwitch = () => {
        setValue(value === 1 ? 0 : 1);
    };

 ......

    useEffect(() => {
        if (value && !isSwitch) {
            return;
        }
        updateDeviceSwitchPinApi();
    }, [value, isSwitch]);
```

<img width="1199" alt="截圖 2022-04-16 下午6 45 33" src="https://user-images.githubusercontent.com/56446970/163672332-35da8cb2-7271-4fb5-8067-f808b755e635.png">

# Task

- [ ] 在 Pin 元件中，修正前端觸發 `devices/{deviceId}/switches/{pinid} api` 的時機
- [ ] 測試使用 Pin 元件時，無論 mode/value 資料為何，皆正常

# Check List

- [x] 使用 Pin 元件時，無論 mode/value 資料為何，皆正常

**Comment by LiangYingC** [comment]
驗證完成
