### ISSUE TITLE
Website - 整理第二階段上線要做的事

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#439]
# Task

- [ ] Review 所有功能和 Style
- [ ] 前 100 名 user 的 isEarlyBird 欄位資料更新
- [ ] migration early adaptor first subscription
- [ ] 準備早鳥會員通知信
- [ ] every8d 簡訊儲值
- [ ] Peter 家 WIFI 帳號密碼修改
