### ISSUE TITLE
Dashboard - 實作 Triggers style

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#446]
# Why
https://github.com/miterfrants/itemhub/milestones/2

Ref: https://www.figma.com/file/eqxlwbzWPRrdMDCede74yX/itemhub?node-id=747%3A9077

# Task

- [x] Triggers List style
- [x] 將 Triggers List filter 改為 search 
- [x] Trigger 能用 name filter feature (after DB / API Trigger Name 加上後)
- [x] Triggers 單一頁面 style

# Check List

- [x] Triggers List
- [x] Triggers 單一頁面

**Comment by miterfrants** [comment]
<img width="636" alt="截圖 2022-05-09 下午9 05 38" src="https://user-images.githubusercontent.com/2028693/167416140-61dda3e9-d24a-42a4-b0b2-4d738b925d7c.png">

如果沒有 PIN 名稱直接用 PIN

**Comment by LiangYingC** [comment]
紀錄：來源裝置以及目標裝置，預設資料均為 `Pin`
