### ISSUE TITLE
Dashboard - Refactor Style

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#465]
# Why
目前每一個頁面的 style 都是自己透過 classname 實作自己的, 沒有把共用的 component 拉出來, 這樣會有漏漏長的 className,

# Task

- [x] 實作 shadow-sm, shadow, shadow-lg
- [x] 實作 rounded-1, rounded-2, rounded-3
- [x] 實作 btn-primary, btn-secondary, btn-danger
- [x] 實作 tag, tag.dsiabled
- [x] 實作 card

# Check List

- [x] 檢查上方這些 class 是否都正常運作 參考資料 https://www.figma.com/file/eqxlwbzWPRrdMDCede74yX/itemhub?node-id=2%3A38
