### ISSUE TITLE
API / Database - 整合 DevicePinSensor 的資料

### ISSUE THREAD

**Issue by LiangYingC** [miterfrants/itemhub#479]
# Why

讓資料庫更乾淨：

- DevicePinName 不需要存在，可以與 DevicePin 整合在一起
- DevicePinSensor 只需要留下 Value / DeviceId 欄位，其他可以整進 DevicePin，再用 DeviceId  關聯的方式拿到 Pin 和 Mode 資料

# Task

- [x] DevicePinSensor 把會與 DevicePinSwitch 共用的欄位合併到 DevicePin 
- [x] DevicePinName 會被移到 DevicePin
- [x] DevicePinSensor 只會留下 Value, DeviceId 欄位, 其他會被移到 DevicePin
- [x] 對外 DevicePinSensor API 資料持一致，從資料庫拿資料的方式需要調整一下

# Check List

- [x] 剩下 DevicePin / DevicePinSensor table，DevicePinName 移除，資料整併進 DevicePin 中
- [x] DevicePinSensor table 剩下 Value, DeviceId 欄位
- [x]  DevicePinSensor 相關 API 依然能正常 CRUD

**Comment by LiangYingC** [comment]
相關討論紀錄：

<img width="780" alt="截圖 2022-04-24 下午3 56 32" src="https://user-images.githubusercontent.com/56446970/164966318-aa3564c3-ccbe-4120-830f-24fdf092bc37.png">
<img width="803" alt="截圖 2022-04-24 下午3 57 00" src="https://user-images.githubusercontent.com/56446970/164966323-ecaa301d-a7eb-42b6-bb7c-0b74a3f917a0.png">
<img width="768" alt="截圖 2022-04-24 下午3 57 09" src="https://user-images.githubusercontent.com/56446970/164966326-fdeb94fd-6aae-4a8c-a0a8-fb2633b6981a.png">
