### ISSUE TITLE
Dashboard - Trigger Delete One 完整功能實作

### ISSUE THREAD

**Issue by LiangYingC** [miterfrants/itemhub#481]
# Why

尚未有 delete trigger 功能，可以直接用 useDeleteTriggersApi 實作

# Task

- [x] 實作 delete single trigger by delete multiple triggers api
- [x] 實作成功刪除多個 triggers 後，會跳出 Toaster
- [x] 實作成功刪除單個 trigger 後，會跳出 Toaster

# Check List

- [x] 確認可以刪除單一 trigger
- [x] 確認可以刪除多個 triggers
- [x] 確認刪除後有跳出 Toaster
