### ISSUE TITLE
Firmware - Implement PIN Auto Generate

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#504]
# Why

- [x] 實作 Auto Generate PIN Firmware

# Task

- [x] Auto Generate PIN Firmware

# Check List

- [x] 下載 Auto Generator 產出的 Firmware 檢查 PIN 資料是否跟資料庫的設定一樣
