### ISSUE TITLE
Website - Implement Feature Style

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#53]
# Why
整修頁面讓它看起來比較不像詐騙集團

# Task
- [x] Feature Basic Style
- [x] Feature 抽出來變成 Component
- [x] Feature RWD
- [x] Feature Page

# Check List
- [x] 檢查 Feature Style 確認是否跟設計稿相同
