### ISSUE TITLE
Dashboard -  trigger-operators 在 dashboard 的 triggers 中顯示要為符號而非中文字

### ISSUE THREAD

**Issue by LiangYingC** [miterfrants/itemhub#563]
# Why

目前 trigger-operators 這個 constants API 回的節點沒有「符號 ex: <, >, <=, >=...」

# Task

- [x] API trigger-operators 要多回大小於的符號
- [x] Dashboard 的 triggers 中，要顯示符號(ex: <)，而非中文字 (ex: 小於)

# Check List

- [ ] API trigger-operators 加上符號
- [ ] Dashboard 的 triggers 中的大小於改為符號
