### ISSUE TITLE
Website - 優化 how to use 的文案

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#608]
# Why

- 增加 how to use 的說明，讓 user 更了解我們的服務 

# Task

- [ ] 增加 how to use 的說明

# Check List

- [ ] 確認 how to use 的文案
- [ ] 新增重新設計 how to use 頁面的 issue
