### ISSUE TITLE
Website - 優化 feature 的文案

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#609]
# Why

- 因為有些說明不清楚，有些功能目前階段沒有提供

# Task

- [ ] feature 的文案調整，修改說明並移除目前沒有提供的服務
- [ ] 實作 feature 文案調整

# Check List

- [ ] 確認 feature 的文案調整

**Comment by vickychou99** [comment]
feature
輕鬆的連接各項裝置
透過 Web 介面設定裝置與 PIN 腳功能後，將我們提供的程式碼打包下載並燒錄至裝置內，即可讓你輕鬆連接並設定裝置。

使用 HTTPS API
使用 HTTP 通訊並使用 SSL 進行加密，藉此建立安全的連線，保障你的資料與安全性。

簡單的操控並運用裝置
透過 Web 介面可操控裝置開關或使用邏輯，較進階的用法只需撰寫少量的程式，即可做各式運用。
