### ISSUE TITLE
DevOps - 降低每個月 GCP 的成本

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#663]
# Why
現在每個月大概要 NTD 7,000, 至少降低 2,000 , 目前看起來可以降低所有 boot disk size 來減少花費

# Task

- [x] 降低 API server boot disk size
- [x] 降低 Website server boot disk size

# Check List

- [ ] deploy 三天後看一下 forcast 金額

**Comment by miterfrants** [comment]
<img width="352" alt="截圖 2022-06-02 上午12 27 49" src="https://user-images.githubusercontent.com/2028693/171453863-d7b23284-a052-48f1-836a-01ee7e3000c1.png">

**Comment by miterfrants** [comment]
<img width="725" alt="截圖 2022-06-06 上午1 34 14" src="https://user-images.githubusercontent.com/2028693/172063006-a0afba7c-5ead-4a6f-bd03-43e50a73a80b.png">
目前從每天約 10USD -> 7USD 每天省 3USD
