### ISSUE TITLE
Research - 研究 matter 可以怎麼運用在 Itemhub 上面

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#764]
# Why

- 目前 IoT 廠商對這個 Protocol 都聲稱未來會是標準

# Task

- [x] 研究 Matter 技術範圍包含
- [x] 研究 Matter 應用

# Check List

- [ ] 用現有的技術類比說明 Matter 技術是什麼
- [ ] 可以怎麼用在 Itemhub

**Comment by miterfrants** [comment]
Matter 統一 IoT Application Layer 並提供 API 給 App 作為控制, 可以把它想像成, 過去大家的電視和遙控器都是用自己的指令集, 現在有統一的指令集控制電視, 如果符合條件就發一個標章給這個電視. 

目前看起來 matter 會在內部網路建立一個 mDNS (實際怎麼運作的還沒有看 code), 我們好像可以建立一個 matter device 透過 browse 的指令取得這個 mDNS 底下的所有裝置.

覺得可能是 ItemHub 的一個切入 2C 的機會, 送一個 Matter Device 到 intranet 把資料送到 ItemHub
