### ISSUE TITLE
Dashboard - Dashboard Monitor

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#768]
# Why
- 讓 Dashboard Page 功能更完整

# Task

- [x] 加上 Sensor Line Chart in Dashboard page
- [x] 加上 Switch in Dashboard page

# Check List

- [ ] 以上 Task 完成
