### ISSUE TITLE
Website - 新增 ga event

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#783]
# Why

- 分析用戶對什麼有興趣

# Task

- [ ] 新增 sign up 的 ga event
- [ ] 新增 how to use basic 的 ga event
- [ ] 新增 how to use google home 的 ga event

# Check List

- [ ] 確認有新增 task 的 ga event
