### ISSUE TITLE
Financial Research

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#8]
# Why 
確認這個市場上下游目前的財務狀況, 看大概能做到的上限大概在哪?
讓自己和團隊比較安心

# Task
- [x] 10 間 IoT 設備公司規模, 投資狀況, 員工人數, 年收入 (option 有可能查不到)
- [x] 10 間 IoT Platform 公司規模, 投資狀況, 員工人數, 年收入 (option 有可能查不到)
- [x] 未來 IoT 設備成長預期

# Check List
- [ ] 產出一個歸納型的 Report
  - [ ] 歸納 IoT 產業的分類
  - [ ] 員工人數的統計資料
  - [ ] 被投資狀況的統計資料
  - [ ] 公司成長趨勢
  - [ ] 這些公司的文化類型
- [ ] 市場現況和趨勢
  - [ ] 現在有賺錢公司的比例
  - [ ] 市場的成長趨勢
  - [ ] 裝置的成長趨勢
- [ ] 我們的優勢
  - [ ] 優勢列點
  - [ ] 可以切入市場的方式

**Comment by miterfrants** [comment]
公司成長趨勢看不出來, 但目前看起來人均產值最高的還是消費性電子, 也許從消費性電子產業切入會是一個不錯的選擇
