### ISSUE TITLE
Dashboard - Monitor RWD

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#825]
# Why
讓使用者可以在小尺寸的裝置上面操作

# Task

- [ ] Dashboard RWD Layout 小尺寸的時候每一個 component 都變成 100% 寬
- [ ] Dashboard Monitor Component RWD
  - [ ] close button 隱藏起來
  - [ ] 文字大縮小

# Check List
<img width="402" alt="截圖 2022-06-29 下午4 10 11" src="https://user-images.githubusercontent.com/2028693/176387324-6ec33848-b69a-4cad-96dd-00c3798d770b.png">

- [ ] 檢查畫面至少要看到資料
