### ISSUE TITLE
Dashboard - 資料庫搬家搬到 Homo 主機上

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#843]
# Why
- 省錢, 目前 GCP SQL 一個月兩千四 

# Task

- [ ] 備份資料庫
- [ ] 還原到 Homo 主機
- [ ] 修改 dbc, 重新 Deploy
- [ ] 自動備份排程
- [ ] 自動檢查備份
- [ ] 暫停 GCP SQL

# Check List

- [ ] 檢查是否正常連線
- [ ] 檢查 GCP SQL 沒有正在運作的 Instance
