### ISSUE TITLE
Operation - Bet 加上 Issue 沒在承諾時間懲罰機制

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#845]
# Why

- 讓工程時程可以預測
- 避免花太多時間在做進度確認

# Task

- [ ] 每日會把即將過期的 Task 按照過期時間列出來提醒參與者
- [ ] 每過期一天會扣除存款中 Task 30% coin e.g: 10 coin task
  - day 1: 扣掉 30% 3 coin 
  - day 2: 扣掉 30% 3 coin
  - day 3: 扣掉 30% 3 coin
  - day 4: 扣掉 100% 10 coin
  - 接下每日扣掉 1 coin
- [ ] 增加暫停執行的功能, 執行人可以提出暫停執行, 要另外一個人 Approve 才會暫停懲罰

# Check List

- [ ] 檢查是否有開始執行懲罰機制
