### ISSUE TITLE
Firmware - RTL8720DN ESP01S 加上 flash mode 說明

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#862]
# Why

- 未來比較好找到要怎麼燒錄

# Task

- [x] RTL8720DN FLash Mode
- [x] ESP01S Flash Mode

# Check List

- [ ] https://github.com/miterfrants/fritzing-itemhub-rtl8720dn-dht11
- [ ] https://github.com/miterfrants/fritzing-itemhub-esp01s-dht11
