### ISSUE TITLE
Website - 加上 sms 通知的說明

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#869]
# Why

- as title

# Task

- [ ] pricingPlan 頁新增 SMS 說明
- [ ] checkout 頁新增 SMS 說明

# Check List

- [ ] 確認 pricingPlan 及 checkout 頁都有新增簡訊說明
