### ISSUE TITLE
Dashboard - Refactor device pin

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#876]
# Why
- 讓程式碼好維護

# Task

- [ ] 建立 device pin component
- [ ] 把 pin 相關的程式碼從 device-pin-data 拉出去

# Check List

- [ ] 確認新增/編輯 pin 的功能正常運作
