### ISSUE TITLE
Website - 評估第三方 mail system 廠商

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#881]
# Why
- sendgrid 100 emails/day，目前有看到其他間免費方案的封數比 sendgrid 還多，ex: sendinblue mailgun mailgun...

# Task

- [ ] 比較其他間第三方 mail system , 如價錢、串接 api 等
- [ ] 確認是否要換第三方 mail system

# Check List

- [ ] 產出 mail system 比較表
- [ ] 如要更換 mail system ，則開新的 issue

**Comment by vickychou99** [comment]
- sendinblue: 9,000/month (300/day)
- mailgun: 5,000 emails/month  + 5 days log (Extra emails beyond trial volume from $1.00 / 1,000 emails)
- Mailchimp 10,000/month (2,000/day)

**Comment by vickychou99** [comment]
使用 Mailchimp 
https://www.nuget.org/packages/MailChimp.Net.V3/

可以研究 sendinblue 的線上客服服務
