### ISSUE TITLE
Platform - Implement IoT Input Device API

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#89]
# Why
Feature

# Task
- [x] 建立 IoT Input Device Table (DevicePinData)
- [x] 實作 Input Device API
- [x] 試著串接硬體裝置把濕度數據送到 API Server

# Check List
- [x] 連到資料庫檢查 DevicePinData 是否有在新增資料 (目前 Peter 這邊有加裝一個濕度感測器每兩秒會送一次房間濕度到 Server)
- [ ] 跟 Peter 取得 Token 檢查一下 API 是否正常運作
  - [x] `GET` https://{{endpoint}}/api/v1/me/devices/56/D1?page=1&limit=100
  - [x] `POST` https://{{endpoint}}/api/v1/me/devices/56/D1
