### ISSUE TITLE
Operation - 把 Firmware 變成獨立的 Submodules 

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#892]
# Why
- 開放給其他人修改 Firmware 
- 讓內部不需要購買這麼多 Device 也能可以 support 這些裝置

# Task

- [x] 研究 submodule
- [x] 跑一次 submodules 的流程
- [x] 撰寫 Firmware Readme

# Check List

- [ ] 有一個 github repo 可以看到 firmware 
- [ ] 同時這個 repo 具備 firmware 會被取代變數的說明

**Comment by vickychou99** [comment]
firmware 會被取代變數的說明在哪兒?
