### ISSUE TITLE
Research - 研究 MQTT 可行性

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#893]
# Why
目前的假設是, 很多使用者註冊了但沒有進到燒錄流程, 猜測的其中一個可能原因是信心不足, 這個信心不足可能包含使用了 HTTP, 在這個前提下, 如果我們把 MQTT 拉到平台來作為通訊的技術, 應該會提升信心. 目前信心不足和使用 MQTT 的關聯性還不是很明確, 所以這邊只做 MQTT 的前期研究, 是否要實作還是等問卷結果在決定

# Task

- [x] .net 實作 MQTT broker
- [x] Arduino 實作 MQTT client
- [x] 整合到現有 api server

# Check List

- [x] 產出一份實作時需要完成的工作項目

**Comment by miterfrants** [comment]
#911 #910
