### ISSUE TITLE
Website - how to use 濕度計更新

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#896]
# Why
- 讓操作說明更清楚

# Task

- [x] 1-2 軟體 - 文字 DHT Library 改成 ->  DHT sensor library
- [x] 3-2 設定 & 下載程式 - 圖改成 ESP 01 S 的圖
- [x] 3-3 - 改寫成讀取濕度感測器，程式碼多了 pins[i].value = valueString;
- [x] 要加上改 WIFI 帳密
- [x] 3-3 選擇晶片類型燒錄，截圖要從 工具進入到燒錄
- [x] 補上 https://arduino-esp8266.readthedocs.io/en/latest/installing.html 加上 JSON 的步驟
- [x] 移掉  #include <ArduinoJson.h> #include <ArduinoUniqueID.h>
- [x] 裝 devicer

# Check List

- [ ] 確認 task 都有執行
