### ISSUE TITLE
API - MQTT DevOps

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#925]
# Why
為支援 MQTT Deployment 和主機做相對應的調整

# Task

- [x] Deployment Script 修改
- [x] Docker File 做相對應的修改 export 1883 Port 
- [x] Production 做相對應的修改

# Check List

- [ ] 可以使用 MQTT Client 連到 Homo 主機
- [ ] 可以使用 MQTT Client 連到 Production 主機
