### ISSUE TITLE
Marketing - 陌生開發

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#946]
# Why

- 推廣服務並獲取心得

# Task

- [ ] 搭訕 IOT 上課的老師
- [ ] 參加 IOT 的展覽
- [ ] 介紹平台服務並產出心得說明

# Check List

- [ ] 確認 task 都有執行

**Comment by vickychou99** [comment]
展覽: https://www.chanchao.com.tw/AutomationTaipei/

**Comment by miterfrants** [comment]
看要不要看到 IoT 教學的老師就寄信給他們

**Comment by vickychou99** [comment]
OK
