### ISSUE TITLE
DevOps - 移機

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#954]
# Why
- 省錢

# Task

**website 移至 api 主機內**
- [x] 把 dashboard / website 移到 api 那台
- [x] 手動建立一個 instance from itemhub-basic-api image
- [x] 複製 website & dashboard nginx config 到手動建立的 instance 
- [x] 重建 itemhub image
- [x] 修改 homo server deploy script 把所有 deploy-xxx.sh -> 全都和併到 deploy.sh
- [x] 把 startup-website-dashboard.sh 放到建立 instance 的 starup script
- [x] 建立新的 load balancer 和新的 instance group 
- [x] 手動跑一次 deploymennt 看一下 instance group 是否有正常更新
- [x] 把 ip 指導新的 load balancer 位置

**homo 主機效能降成 e2-small**
- [x] 手動建立一個 image from develop
- [x] 用新建立的 image 建立 instance ，主機改成 e2-small 
- [x] docker start 各專案的 image 
   - [x] why-children-philosophy-sms-api
   - [x] itemhub-api
   - [x] chenandchou-website
   - [x] cb-burma-multiple-lang
   - [x] cathayconsult-website-app
   - [x] cathayconsult-cms-api
   - [x] ziip-dashboard-api
   - [x] ziip-website-api
   - [x] ziip-website-f2e
   - [x] mysql
   - [x] the-chen-lab-api
   - [x] chenandchou-cms-api
   - [x] homo-bet-api
   - [x] cathayconsult-cms-file-api
   - [x] ccnb-erp-api
   - [x] kylemanna/openvpn
   - [x] cathayconsult-website-api
   - [x] mcr.microsoft.com/mssql/server:2017-latest-ubuntu

# Check List

- [x] 完成移機
