### ISSUE TITLE
DevOps - DB 移機 

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#957]
# Why
省錢

# Task

- [x] 在 gcp 上開一台 e2-standard 主機
- [x] 在新開的主機上安裝 mysql
- [x] 裝好之後還原資料庫備份檔
- [x] 修改兩台 api 主機的連線資訊

# Check List

- [x] 確認上述 task 都有執行
